name: "CloudFlare DNS: Create or Update Record"
description: "Create or Update DNS Record on CloudFlare"
author: "Bluesboy"

inputs:
  type:
    description: 'Record Type (A, CNAME, NS, etc.)'
    required: true
  name:
    description: 'Full Record Name (record.example.com)'
    required: true
  content:
    description: 'Record Content (8.8.8.8, example.com)'
    required: true
  ttl:
    description: 'Record TTL in seconds ("1" is "Auto", set by default)'
    default: 1
  proxied:
    description: 'Use CloudFlare Proxy (boolean, "true" by default)'
    default: true
  token:
    description: "CloudFlare API token"
    required: true
  zone:
    default: "CloudFlare Zone ID"
    required: true

outputs:
  record_id:
    description: "Record ID"
  name:
    description: 'Record Name'

runs:
  using: "node12"
  main: "main.js"

branding:
  icon: "at-sign"
  color: "orange"
